# Generated by Django 4.2.13 on 2024-07-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_add_initial_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='student_management_app.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('Mathematics', 'Mathematics - Course covering algebra, geometry, and calculus'), ('Science', 'Science - Course covering physics, chemistry, and biology'), ('English', 'English - Course covering literature, grammar, and composition'), ('History', 'History - Course covering ancient, medieval, and modern history'), ('Physical Education', 'Physical Education - Course focusing on physical fitness and sports')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('Fail', 'Fail')], max_length=5),
        ),
    ]
