# Generated by Django 4.2.13 on 2024-07-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_timetableentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_pdfs/'),
        ),
    ]
