# Generated by Django 4.2.13 on 2024-07-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management_app', '0002_department_rename_position_staff_role_staff_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='profile_picture',
        ),
    ]
