# Generated by Django 4.2.13 on 2024-07-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management_app', '0003_remove_qualification_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.AddField(
            model_name='qualification',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='staff_qualifications', to='staff_management_app.staff'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='staff_responsibilities', to='staff_management_app.staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='departments',
            field=models.ManyToManyField(related_name='staff_members', to='staff_management_app.department'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff/profile_pics/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.TextField(default='staff'),
        ),
    ]
