# Generated by Django 4.2.13 on 2024-07-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management_app', '0004_remove_staff_department_qualification_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('English Department', 'English Department'), ('Mathematics Department', 'Mathematics Department'), ('Science Department', 'Science Department'), ('Social Studies Department', 'Social Studies Department'), ('Foreign Languages Department', 'Foreign Languages Department'), ('Physical Education Department', 'Physical Education Department'), ('Arts Department', 'Arts Department'), ('Administration', 'Administration'), ('Special Education Department', 'Special Education Department'), ('Counseling Department', 'Counseling Department')], max_length=100),
        ),
    ]
