# Generated by Django 4.2.13 on 2024-06-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='apply_leave',
            field=models.BooleanField(default=False),
        ),
    ]
