# Generated by Django 4.2.13 on 2024-07-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='employee_id',
            new_name='admin_id',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='employee_id',
            new_name='staff_id',
        ),
    ]
