# Generated by Django 4.2.13 on 2024-07-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='Group',
            field=models.ManyToManyField(blank=True, related_name='admin', to='auth.group'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='Groups',
            field=models.ManyToManyField(blank=True, related_name='staff', to='auth.group'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Groups',
            field=models.ManyToManyField(blank=True, related_name='students', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='users', to='auth.group', verbose_name='groups'),
        ),
    ]
