# Generated by Django 4.2.13 on 2024-07-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registration_app', '0005_adminprofile_group_adminprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_student',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
